spring:
  mvc:
    servlet:
      path: /starter
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb;MODE=MySQL;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password:
  sql:
    init:
      schema-locations: classpath:schema.sql
      data-locations: classpath:data.sql
      username: sa
      password:
  h2:
    console:
      enabled: true
